services:
  anime-calendar:
    build:
      context: ./
      dockerfile: prod.Dockerfile.yml
    restart: always
    ports:
      - 8080:3000
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
