version: '3'

services:
  anime-calendar:
    build:
      context: ./deploy
      dockerfile: prod.Dockerfile.yml
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
    restart: always
    ports:
      - 8080:3000
    networks:
      - dokploy-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.<unique-name>.rule=Host(`your-domain.com`)'
      - 'traefik.http.routers.<unique-name>.entrypoints=websecure'
      - 'traefik.http.routers.<unique-name>.tls.certResolver=letsencrypt'
      - 'traefik.http.services.<unique-name>.loadbalancer.server.port=3000'
networks:
  dokploy-network:
    external: true
