services:
  anime-calendar:
    build:
      context: ./
      dockerfile: prod.Dockerfile.yml
    restart: always
    environment:
      - DENO_VERSION=${DENO_VERSION}
    ports:
      - ${PORT}:3000
    networks:
      - dokploy-network
    labels:
      - 'traefik.enable=true'
  #  - 'traefik.http.routers.anime.entrypoints=web'
  #  - 'traefik.http.routers.anime.rule=HostRegexp(`anime.{ip:.*}.traefik.me`)'
  #  - 'traefik.http.services.anime.loadbalancer.server.port=${INTERNAL_PORT}'
networks:
  dokploy-network:
    external: true
