services:
  anime-calendar:
    build:
      context: ./
      dockerfile: prod.Dockerfile.yml
    restart: always
    ports:
      - ${PORT}:3000
    networks:
      - dokploy-network
    labels:
      - 'traefik.enable=true'
networks:
  dokploy-network:
    external: true
