FROM denoland/deno:ubuntu-2.4.1 AS builder

WORKDIR /app

RUN chown deno:deno /app/

COPY package*.json .
COPY deno*.json .

RUN deno install  --allow-scripts

COPY . .

RUN deno task build

FROM denoland/deno:ubuntu-2.4.1

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/package.json .
COPY --from=builder /app/deno.json .

USER deno

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "run","--allow-read=.","--allow-env","--allow-net", "build/index.js"]
