FROM denoland/deno:ubuntu-2.2.0 as builder
ARG DENO_VERSION
ENV DENO_VERSION=$DENO_VERSION
ENV DENO_IMAGE=denoland/deno:ubuntu-$DENO_VERSION


WORKDIR /app
RUN echo "Deno $DENO_VERSION $DENO_IMAGE"
RUN chown deno:deno /app/

COPY package*.json .
COPY deno*.json .

RUN deno install  --allow-scripts

COPY . .

RUN deno task build

FROM $DENO_IMAGE 

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/package.json .

USER deno

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "run","--allow-read=.","--allow-env","--allow-net", "build/index.js"]
