FROM denoland/deno:alpine-2.1.4 AS builder

WORKDIR /app

USER deno 

COPY package*.json .

RUN deno task

RUN deno install --allow-scripts

COPY . .

RUN deno task build

FROM denoland/deno:alpine-2.1.4

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/package.json .

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "run","--allow-read=.","--allow-env","--allow-net", "build/index.js"]