FROM denoland/deno:2.1.4

WORKDIR /app

USER deno 

COPY package*.json .
COPY deno.lock .

RUN deno install 

COPY . .

RUN deno task build

FROM denoland/deno:2.1.4

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/package.json .

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "run","--allow-read=.","--allow-env","--allow-net", "build/index.js"]