name: Take master to develo on tag creation

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '!**SNAPSHOT'
      - '!**RC'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Imprimir github.ref
        run: echo El valor de github.ref es ${{ github.ref }}
      - run: gh pr create -B $DESTINATION -H master --title "Merge master into $DESTINATION" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION: develop
