name: Take master to develo on tag creation

on:  
  push:
      tags:
      - '*'
      - '!**SNAPSHOT'
      - '!**RC'
      branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Imprimir github.ref con debug-action
        uses: actions/debug@v1
        with:
          github_ref: ${{ github.ref }}
      - run: gh pr create -B $DESTINATION -H master --title "Merge master into $DESTINATION" --body "Created by Github action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION: develop
        