name: Take master to develo on tag creation

on:  
  push:
    tags:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create -B master -H $DESTINATION --title 'Merge master into $DESTINATION' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION: develop
        