name: Take master to develo on tag creation

on:  
  push:
    tags:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        run: gh pr create -B master -H develop --title 'Merge master into develop' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        